### ISSUE TITLE
Biosweep odd image issue

### ISSUE THREAD

**Issue by stromme** [stromme/stromme#58]
Hey Josua,

For some reason there's at least one image on the Biosweep site that is being cut off, but only for non-logged in users. Appears fine for logged in users. very odd.

ex. http://biosweepny.com/medical/ - "Surface Defence" image

Not logged in: https://www.dropbox.com/s/zwd8oozn7v0ynqh/Screenshot%202015-01-12%2018.06.30.png?dl=0

Logged in: https://www.dropbox.com/s/rqrz8vmmpjcerg9/Screenshot%202015-01-12%2018.08.09.png?dl=0

Ideas?

**Comment by josualeonard** [comment]
There is special functionality when an superadmin logged in. It's to enable image changes on live view. But there is one unnecessary line added, getting image full size. That caused it to show full size on admin logged in.

Fixed. Now consistent. I also adjusted size of images below it.

![screen shot 2015-01-13 at 6 41 59 pm](https://cloud.githubusercontent.com/assets/1229872/5720236/0738938e-9b54-11e4-9a70-2ac23b6457b5.png)
